name: Compat Request
description: Make this mod compatible with another mod and datapack.
title: "[Compat]: "
labels: [ "Mod Compat" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your supporting!
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: The name of your mod. You can also leave a link here.
      placeholder: ex. Ocean World
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of your mod
      description: What can Biome Modifier for Fabric mod do for your mod?
      placeholder: Ask anything you want.
    validations:
      required: true