name: Bug Report
description: Report any bugs here! Report crashes using "Crash Report"
title: "[Bug]: "
labels: [ "Bug Minor" ]
body:
  - type: markdown
    attributes:
      value: |
        **Please try following steps before report and tell me if the crash reproduces:**
        
        - Delete the config file to reset the config.
        
        - Tries Biome Modifier for Fabric mod alone (with its dependency).
        
        - Find the smallest reproducible set of this crash - for example, if this crash occurs when you only install biome_modifier, emeraldcraft, and terrablender, even if you add some new mods, the smallest reproducible set is the three mods mentions above if the same crash occurs.
  - type: input
    id: mod-version
    attributes:
      label: The Version of Biome Modifier for Fabric
      description: |
        What version are you using when this crash occurs?
      placeholder: ex. 1.20.1+1.0.1
    validations:
      required: true
  - type: input
    id: datapack-name
    attributes:
      label: Datapack
      description: |
        Which datapacks are you using? Please also leave links of them.
        Biome Modifier for Fabric won't work alone without datapacks. However, if you crash without any datapacks, specify N/A.
      placeholder: ex. Always Working Bed
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of minecraft are you using?
      placeholder: ex. 1.20.2
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: What Mod Loader are you running?
      options:
        - Forge
        - Fabric
        - Quilt
        - NeoForge
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you using?
      placeholder: ex. 0.16.0
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of the bug would you describe?
      options:
        - Biome Modifier
        - Dimension Modifier
        - Noise Generator Modifier
        - Example Datapacks
        - Documentation mismatched with APIs
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: How to reproduce the bug?
      placeholder: Tell us what you see, and also, any other mods you are using?
    validations:
      required: true
  - type: textarea
    id: debug-log
    attributes:
      label: latest.log/debug.log
      description: If you can't make it clear enough, or this bug cannot be reproduce sometimes, please upload your latest.log/debug.log file. You can use https://gist.github.com/ and leave the link here.
      placeholder: Drag and drop latest.log/debug.log file here or link it with https://gist.github.com/!
    validations:
      required: false
  - type: dropdown
    id: isolate-mod
    attributes:
      label: Did you isolate Biome Modifier for Fabric?
      description: |
        Did you try a separate instance with Biome Modifier for Fabric only and its required dependencies?
      options:
        - I tried Biome Modifier for Fabric alone and the crash occurs.
        - I tried Biome Modifier for Fabric alone and the crash doesn't occurs.
        - I didn't try Biome Modifier for Fabric alone.
    validations:
      required: true